export const EDIT_PROFILE = "EDIT_PROFILE"
export const EDIT_APPLIED_TOPIC  = "APPLIED_TOPIC";
export const INTIAL = "INTIAL"
export const EDIT_PROF_TIMELINE = "EDIT_PROF_TIMELINE"
export const EDIT_LOADER = "EDIT_LOADER"